{% set name = "rubyzip" %}
{% set version = "2.3.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 80d2d0a5c5fc21d2ef59a0e830ef3a6a68df4be3530370878884eacdf20b9615

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r zip -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: BSD-2-Clause
  license_family: BSD
  license_file: license.txt
  summary: rubyzip is a ruby module for reading and writing zip files

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/rubyzip/{{ name }}

extra:
  recipe-maintainers:
    - sodre
