travis:
  secure:
    BINSTAR_TOKEN: U/0RfR2aNZ2PjGyTLkPSWAd0Qvzagrp5iMog23VXEL2w5GskBe1syCrE6GRtsHHNqTREWAL4Wq+PZElzTbi7Ql5EjOwKCJK4b+W1zaKCP0u5dN13GcQQSx8cKw3XG69yQX+Tv1EDd6Lj3Stq410xnKwKm4datWBKODB9RGiUuf6xGgSkaFu6AaVtFUxtofD3jPHGzbNY9PyrwIhn75tcTqGHcMHLCjBy+biadBibByIP+iGalg3FdE6RNpP6hswBk8bgzeTJgUqxCYmS0Nf/OBY1N6XcRPudCZosc6J8EUAYVR4AEbd+lrzIZItqmPx2rmVrujrZJCtTDZK9YTJTp2+LO3i/SWaHMG2CbyRNuABRfFwg2iBYajdcK1LBTU7UztmdEnPSVWf9QELgf7s98jtR4litJtUfvYzWMrRVT8vTbcRZoCF/j9dnJPXvHY0FE/ZMupG1veRCzddxzlaz+lK3za4h0lKfAwXQCAvs1wUWENnPsbjrmSdO3Jol5jCZjV50VaKrdsMdxSOcAEZuqQEMp/5JMY+pjqSV24ECgNHwjsruJ0V9Vg4lCLhiMrYZzCPseR5FXnT23SP8BDIrEVXI0VfQyszSLZz7gXwArr4AyIJlhPfWM1sA8B4HDY4UKEhzzRxgXlS+X4SH1nFWgty4O5TaggoVfu5eKVnRqZA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
